# Generated by Django 4.2.1 on 2024-02-02 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Form Type',
                'verbose_name_plural': 'Form Types',
                'db_table': 'form_type',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('form_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.formtype')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('whetter_description', models.TextField()),
                ('consumables', models.BooleanField(default=False)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estacion.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenance',
                'db_table': 'Maintenance',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('observations', models.TextField()),
                ('maintenance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.maintenance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'db_table': 'answer',
            },
        ),
    ]
